vxcontrol/soldr

build/package/agent/Dockerfile, build/package/agent/build-install-linux.sh
Fix errors when build agent docker and installer
=> Fix agent build docker and installer

build/package/agent/DEBIAN/postinst, build/package/agent/RPM/rpm.spec, build/package/agent/build-install-linux.sh
More fixes for installer agent linux
=> Fix agent linux installer

Makefile, web/libs/features/modules-interactivity/src/lib/components/module-page/module-page.component.scss
=> fix(ui): broken build

web/libs/styles/src/lib/design-tokens/legacy-2017/element-ui/_element-variables.scss, web/libs/styles/src/lib/design-tokens/pt-2022/element-ui/_element-variables.scss, web/libs/styles/src/lib/element-ui/components/checkbox.scss, web/libs/styles/src/lib/element-ui/components/loading.scss, web/libs/styles/src/lib/overriden-vue/_overriden-vue.theme.scss
=> fix: yara scanner validation

web/libs/store/modules/src/lib/edit/module-edit.reducer.ts
insert localization for event keys on manual editing
=> fix(ui): insert localization for event keys

web/libs/api/src/lib/dto/agents.ts, web/libs/api/src/lib/dto/policies.ts, web/libs/api/src/lib/services/agents.service.ts, web/libs/api/src/lib/services/policies.service.ts, web/libs/features/agents/src/lib/routes/agents-page/agents-page.component.ts, web/libs/features/modules/src/lib/features-modules.module.ts, web/libs/features/policies/src/lib/utils/default-filters.ts, web/libs/shared/src/lib/components/groups-and-filters/groups-and-filters.component.html, web/libs/shared/src/lib/shared.module.ts, web/libs/store/agents/src/lib/list/agent-list.actions.ts, web/libs/store/agents/src/lib/list/agent-list.effects.ts, web/libs/store/agents/src/lib/list/agent-list.reducer.ts, web/libs/store/agents/src/lib/list/agent-list.selectors.ts, web/libs/store/policies/src/lib/policies.actions.ts, web/libs/store/policies/src/lib/policies.effects.ts, web/libs/store/policies/src/lib/policies.reducer.ts, web/libs/store/policies/src/lib/policies.selectors.ts
heavy requests of counters for agents and policies replaced to optimized
=> fix(ui): optimized requests of counters for agents and policies

web/libs/store/modules/src/lib/edit/module-edit.reducer.ts
fix error on saving of module after remove required param
=> fix: error on saving of module

.github/workflows/ci.yml, build/package/agent/Dockerfile_cross
Fixed local call reusable workflow to unlocal
=> Fix reusable workflow on local runs

web/libs/shared/src/lib/components/secure-module-config/secure-module-config.component.html, web/libs/shared/src/lib/components/secure-module-config/secure-module-config.component.ts
Fixed rendering with different widget types
=> fix(ui): secure params rendering with different widget types

web/libs/shared/src/lib/utils/get-empty-schema.ts, web/libs/store/modules/src/lib/edit/module-edit.reducer.ts
Fixed error on saving module after removing all params
=> fix(ui): error on saving module after removing all params

web/libs/features/policies/src/lib/services/link-policy.facade.service.ts, web/libs/shared/src/lib/components/modules-config/modules-config.component.html, web/libs/shared/src/lib/components/ncform-wrapper/ncform-wrapper.component.ts, web/libs/styles/src/lib/overriden-vue/_overriden-vue.scss
* screen flashing in secure configuration
* conflict groups in policies
* type number in event config
=> fix(ui): event config, conflict groups, screen flashing

.github/ISSUE_TEMPLATE/1-bug-report.yml, .github/ISSUE_TEMPLATE/2-enhancement.yml, .github/PULL_REQUEST_TEMPLATE.md, .github/SAVED_REPLIES.md
Similar templates as in https://github.com/vxcontrol/soldr-modules/pull/7
=> [issue-2] add templates

web/libs/features/agents/src/lib/routes/agent-module-page/agent-module-page.component.html, web/libs/features/agents/src/lib/routes/agent-module-page/agent-module-page.component.ts, web/libs/features/groups/src/lib/routes/group-module-page/group-module-page.component.html, web/libs/features/groups/src/lib/routes/group-module-page/group-module-page.component.ts, web/libs/features/modules-interactivity/src/lib/components/module-page/module-page.component.html, web/libs/features/modules-interactivity/src/lib/components/module-page/module-page.component.ts, web/libs/features/policies/src/lib/routes/policy-module-page/policy-module-page.component.html, web/libs/features/policies/src/lib/routes/policy-module-page/policy-module-page.component.ts, web/libs/shared/src/lib/components/action-details-panel/action-details-panel.component.html, web/libs/shared/src/lib/components/action-details-panel/action-details-panel.component.ts, web/libs/shared/src/lib/components/event-details-panel/event-details-panel.component.html, web/libs/shared/src/lib/components/event-details-panel/event-details-panel.component.ts, web/libs/shared/src/lib/components/module-config/module-config.component.html, web/libs/shared/src/lib/components/module-config/module-config.component.ts, web/libs/store/modules-instances/src/lib/modules-instances.actions.ts, web/libs/store/modules-instances/src/lib/modules-instances.effects.ts, web/libs/store/modules-instances/src/lib/modules-instances.facade.service.ts, web/libs/store/modules-instances/src/lib/modules-instances.reducer.ts, web/libs/store/modules-instances/src/lib/modules-instances.selectors.ts
fixed errors with hint "edit in policy" and availability of buttons in module configuration from agent context.
=> fix: hint "edit in policy" and availability of buttons in the module configuration

web/libs/store/policies/src/lib/policies.reducer.ts
fix error saving changes in module configuration
=> fix: save event changes in module configuration

internal/app/api/server/private/binaries.go, internal/app/api/server/private/events.go, internal/app/api/server/private/groups.go, internal/app/api/server/private/modules.go, internal/app/api/server/private/options.go, internal/app/api/server/private/policies.go, internal/app/api/server/private/porting.go, internal/app/api/server/private/roles.go, internal/app/api/server/private/services.go, internal/app/api/server/private/tags.go, internal/app/api/server/private/tenants.go, internal/app/api/server/private/upgrades.go, internal/app/api/server/private/users.go, internal/app/api/server/private/versions.go, internal/app/api/server/router.go
* I've created services structs and wrap handlers in it for passing explicit dependencies into services.
* Remove context usage for obtaining global DB instance in handlers.
=> Use global DB instance as service dependency

internal/app/api/docs/docs.go, internal/app/api/docs/swagger.json, internal/app/api/docs/swagger.yaml, internal/app/api/server/events/poller.go, internal/app/api/server/private/binaries.go, internal/app/api/server/private/modules.go, internal/app/api/worker/module_syncer.go, web/libs/api/src/lib/dto/events.ts, web/libs/features/groups/src/lib/routes/group-module-page/group-module-page.component.ts, web/libs/features/groups/src/lib/routes/group-page/group-page.component.ts, web/libs/features/policies/src/lib/routes/policy-module-page/policy-module-page.component.ts, web/libs/features/policies/src/lib/routes/policy-page/policy-page.component.ts, web/libs/shared/src/lib/components/events-grid/events-grid.component.html, web/libs/store/groups/src/lib/groups.actions.ts, web/libs/store/groups/src/lib/groups.effects.ts, web/libs/store/groups/src/lib/groups.facade.ts, web/libs/store/groups/src/lib/groups.reducer.ts, web/libs/store/groups/src/lib/groups.selectors.ts, web/libs/store/modules-instances/src/lib/modules-instances.actions.ts, web/libs/store/modules-instances/src/lib/modules-instances.effects.ts, web/libs/store/modules-instances/src/lib/modules-instances.facade.service.ts, web/libs/store/modules-instances/src/lib/modules-instances.reducer.ts, web/libs/store/modules-instances/src/lib/modules-instances.selectors.ts, web/libs/store/policies/src/lib/policies.actions.ts, web/libs/store/policies/src/lib/policies.effects.ts, web/libs/store/policies/src/lib/policies.facade.ts, web/libs/store/policies/src/lib/policies.reducer.ts, web/libs/store/policies/src/lib/policies.selectors.ts
Queries for the list of all agents have been optimized
> Fixed - performance issues
=> fix(ui): request of all agents optimized

db/api/migrations/0002_add_user_password_change_flag.sql, db/api/seed.sql, internal/app/api/docs/docs.go, internal/app/api/docs/swagger.json, internal/app/api/docs/swagger.yaml, internal/app/api/models/users.go, internal/app/api/server/private/users.go, internal/app/api/server/public/info.go
The flag is automatically returned in "/info" API call which can be then used by a FE to decide that notification need to be shown to a user.
Partially Closes #60
Check that API re
> Changed - API "/info" extended with password_change_required flag
=> return password_change_required flag

db/api/migrations/0002_add_user_password_change_flag.sql, internal/app/api/models/users.go, internal/app/api/server/private/users.go
Some stuff was missed in previous PR
Fix f the previous PR.
* Missed reverse migration
* gorm missed update field
* change for "min" length of current password so we would be able to actually change default one
=> missed fixes for password change request

web/libs/features/modules/src/lib/components/edit-dependencies-section/edit-dependencies-section.component.html, web/libs/features/modules/src/lib/components/edit-secure-config-section/edit-secure-config-section.component.html, web/libs/shared/src/lib/components/assigning-actions-master/assigning-actions-master.component.ts, web/libs/shared/src/lib/components/assigning-actions-to-event/assigning-actions-to-event.component.ts
* fixed removing event actions
* fixed ions
=> fix(ui): fixed removing event actions

web/libs/features/modules/src/lib/components/edit-actions-section/edit-actions-section.component.ts, web/libs/features/modules/src/lib/components/edit-changelog-section/edit-changelog-section.component.ts, web/libs/features/modules/src/lib/components/edit-config-section/edit-config-section.component.ts, web/libs/features/modules/src/lib/components/edit-dependencies-section/edit-dependencies-section.component.ts, web/libs/features/modules/src/lib/components/edit-events-section/edit-events-section.component.ts, web/libs/features/modules/src/lib/components/edit-fields-section/edit-fields-section.component.ts, web/libs/features/modules/src/lib/components/edit-general-section/edit-general-section.component.ts, web/libs/features/modules/src/lib/components/edit-localization-section/edit-localization-section.component.ts, web/libs/features/modules/src/lib/components/edit-secure-config-section/edit-secure-config-section.component.ts
Method `requestSubmit` replaced to dispatch event `submit` for forms in sytem module.
Closes #
Saving the system module should work in supported browsers.
=> fix(ui): doesn't work saving in system module in safari

web/libs/shared/src/lib/components/modules-config/modules-config.component.ts
The logic of displaying agent dependencies has been changed, the type of dependency on the agent version has been added.
Closes #
Check agent module status display for unresolved and resolved dependencies (on agent version)
=> fix(ui): unresolved agent version dependency appears as resolved

web/libs/core/src/lib/services/monaco.service.ts
Dark theme in monaco is restored after failed bugfix (https://github.com/vxcontrol/soldr/pull/48)
Closes #
Monaco editor in module interactivity, event viewer and file editor in system module should be with dark theme.
=> fix(ui): restored dark theme monaco

web/libs/features/agents/src/lib/components/edit-agent-modal/edit-agent-modal.component.html, web/libs/features/groups/src/lib/components/edit-group-modal/edit-group-modal.component.html, web/libs/features/modules/src/lib/components/toggle-item/toggle-item.component.ts, web/libs/features/policies/src/lib/components/edit-policy-modal/edit-policy-modal.component.html, web/libs/i18n-resources/en-US/common.json, web/libs/i18n-resources/ru-RU/common.json
Fixed incorrect counting of the number of event/action variables and fixed validation of long entity names
=> fix(ui): invalid fields count and validation long names

Makefile, build/package/dbmigrate/entrypoint.sh, db/api/seed.sql, pkg/app/api/modules/modules.go, pkg/app/api/server/private/helpers.go, pkg/app/api/server/private/modules.go, pkg/app/api/server/private/options.go, pkg/app/api/server/private/policies.go, pkg/app/api/server/private/porting.go, pkg/app/api/server/private/upgrades.go, pkg/app/api/worker/module_syncer.go, pkg/controller/controller.go
It's refactoring need because some changes was synchronized incorrectly.
Please, looking up commits tab.
* Changed - [moved getService and getDBEncryptor functions to private pacage](https://github.com/vxcontrol/soldr/commit/50363c5946819e17dff6641a2154bcc1ef0d3aec)
* Fixed - 
[bug with missing of updating modules on loading controller phase](https://github.com/vxcontrol/soldr/commit/f818d4e89a51a6d1892b31d186b35aee13c46e84);
[fix: bug with can not loading modules in server application until api server will not update instance modules into vx_instance DB](https://github.com/vxcontrol/soldr/commit/b9b6cba2a9c3d8f9282c7d8efe7bc9340fb43183);
[fix: bug using 'make db-seed' command and after that running server and api services (can't migrate data into …
=> Refactoring after sync

web/libs/features/policies/src/lib/routes/policies-page/policies-page.component.html, web/libs/shared/src/lib/components/policies-grid/policies-grid.component.html
Default state for column "Consistency" in policies grid
Closes #
=> fix(ui):consistency in policies grid is hidden by default

web/libs/features/policies/src/lib/routes/policies-page/policies-page.component.html, web/libs/shared/src/lib/components/policies-grid/policies-grid.component.html
=> Revert "fix(ui):consistency in policies grid is hidden by default"

web/libs/features/modules/src/lib/routes/edit-module-page/edit-module-page.component.ts, web/libs/i18n-resources/en-US/modules.json, web/libs/i18n-resources/en-US/shared.json, web/libs/i18n-resources/ru-RU/modules.json
=> fix(ui): change save module dialog, add splitter in assigning action master dialog title

web/libs/styles/src/lib/ag-grid/_ag-grid-theme.scss
=> fix(ui): removed scroll on assigning actions

web/libs/features/modules-interactivity/src/lib/components/grid/grid.component.js, web/libs/styles/src/lib/overriden-vue/_overriden-vue.theme.scss
=> fix(ui): small fixes vue grid

web/libs/features/modules/src/lib/components/create-module-modal/create-module-modal.component.html, web/libs/features/modules/src/lib/components/create-module-modal/create-module-modal.component.ts, web/libs/shared/src/lib/components/autocomplete-tags/autocomplete-tags.component.html, web/libs/shared/src/lib/components/autocomplete-tags/autocomplete-tags.component.ts
- invalid tag validation with a copy
- validation module name length
=> fix(ui): tags & modules validation

web/extra-webpack.config.js, web/package-lock.json, web/package.json
=> fix(ui): enable optimize minification

web/libs/features/modules/src/lib/components/edit-changelog-section/edit-changelog-section.component.ts
=> fix(ui): duplicated changelog

web/libs/i18n-resources/en-US/shared.json, web/libs/i18n-resources/ru-RU/shared.json, web/libs/shared/src/lib/components/module-config-block/module-config-block.component.html, web/libs/shared/src/lib/components/module-config-block/module-config-block.component.ts, web/libs/shared/src/lib/components/modules-config/modules-config.component.html, web/libs/shared/src/lib/components/modules-config/modules-config.component.ts, web/libs/store/modules-instances/src/lib/modules-instances.effects.ts
=> fix(ui): config save button

web/libs/features/modules/src/lib/routes/modules-page/modules-page.component.ts, web/libs/shared/src/lib/components/grid/grid.component.ts, web/libs/store/modules/src/lib/list/module-list.effects.ts, web/package-lock.json
=> fix(ui): double focus in grids
